-- ============================================================
-- AEROERP - INDIA AEROSPACE INDUSTRY INTELLIGENCE ERP
-- Oracle Database Schema (DDL)
-- Version: 1.0  |  Author: Mahin  |  Year: 2025
-- ============================================================

-- ── SEQUENCES ────────────────────────────────────────────────
CREATE SEQUENCE SEQ_COMPANY         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CONTACT         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_OPPORTUNITY     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_JOB             START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TECHNOLOGY      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SUPPLIER        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PROJECT         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DOCUMENT        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CRM_ACTIVITY    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_USER            START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ROLE            START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AUDIT           START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LOOKUP          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ============================================================
-- LOOKUP / REFERENCE TABLES
-- ============================================================
CREATE TABLE REF_LOOKUP (
    LOOKUP_ID       NUMBER         DEFAULT SEQ_LOOKUP.NEXTVAL PRIMARY KEY,
    LOOKUP_TYPE     VARCHAR2(50)   NOT NULL,   -- 'COMPANY_TYPE','SEGMENT','STATUS', etc.
    LOOKUP_CODE     VARCHAR2(50)   NOT NULL,
    LOOKUP_VALUE    VARCHAR2(200)  NOT NULL,
    SORT_ORDER      NUMBER         DEFAULT 0,
    IS_ACTIVE       CHAR(1)        DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_ON      DATE           DEFAULT SYSDATE,
    CONSTRAINT UQ_LOOKUP UNIQUE (LOOKUP_TYPE, LOOKUP_CODE)
);
COMMENT ON TABLE REF_LOOKUP IS 'Master lookup/reference data for all dropdown values';

-- Seed lookups
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('COMPANY_TYPE','PSU','PSU (Govt. Enterprise)',1);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('COMPANY_TYPE','PRIVATE','Private',2);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('COMPANY_TYPE','STARTUP','Startup',3);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('COMPANY_TYPE','MNC','MNC Subsidiary',4);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('COMPANY_TYPE','JV','Joint Venture',5);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('COMPANY_TYPE','GOVT','Govt. Department',6);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('SEGMENT','DEFENCE','Defence Aerospace',1);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('SEGMENT','COMMERCIAL','Commercial Aviation',2);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('SEGMENT','SPACE','Space Technology',3);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('SEGMENT','UAV','UAV / Drone',4);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('SEGMENT','MFG','Aerospace Manufacturing',5);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('SEGMENT','MRO','MRO',6);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('SEGMENT','AVIONICS','Avionics',7);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('SEGMENT','SOFTWARE','Aerospace Software & Eng.',8);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('OPP_STATUS','NEW','New',1);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('OPP_STATUS','QUALIFIED','Qualified',2);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('OPP_STATUS','PROPOSAL','Proposal Submitted',3);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('OPP_STATUS','NEGOTIATION','Negotiation',4);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('OPP_STATUS','WON','Won',5);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('OPP_STATUS','LOST','Lost',6);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('OPP_STATUS','HOLD','On Hold',7);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('JOB_STATUS','OPEN','Open',1);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('JOB_STATUS','APPLIED','Applied',2);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('JOB_STATUS','INTERVIEW','Interview Scheduled',3);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('JOB_STATUS','OFFERED','Offer Received',4);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('JOB_STATUS','ACCEPTED','Accepted',5);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('JOB_STATUS','REJECTED','Rejected',6);
INSERT INTO REF_LOOKUP (LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,SORT_ORDER) VALUES ('JOB_STATUS','CLOSED','Closed',7);

COMMIT;

-- ============================================================
-- MODULE 0 – USERS & ROLES (SECURITY)
-- ============================================================
CREATE TABLE ERP_ROLES (
    ROLE_ID         NUMBER         DEFAULT SEQ_ROLE.NEXTVAL PRIMARY KEY,
    ROLE_NAME       VARCHAR2(50)   NOT NULL UNIQUE,
    ROLE_DESC       VARCHAR2(200),
    IS_ACTIVE       CHAR(1)        DEFAULT 'Y',
    CREATED_ON      DATE           DEFAULT SYSDATE
);

CREATE TABLE ERP_USERS (
    USER_ID         NUMBER         DEFAULT SEQ_USER.NEXTVAL PRIMARY KEY,
    USERNAME        VARCHAR2(50)   NOT NULL UNIQUE,
    EMAIL           VARCHAR2(100)  NOT NULL UNIQUE,
    PASSWORD_HASH   VARCHAR2(256)  NOT NULL,
    FULL_NAME       VARCHAR2(100),
    MOBILE          VARCHAR2(15),
    ROLE_ID         NUMBER         NOT NULL REFERENCES ERP_ROLES(ROLE_ID),
    IS_ACTIVE       CHAR(1)        DEFAULT 'Y',
    LAST_LOGIN      TIMESTAMP,
    CREATED_ON      DATE           DEFAULT SYSDATE,
    CREATED_BY      NUMBER
);

CREATE TABLE ERP_MODULE_PERMISSIONS (
    PERM_ID         NUMBER         GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROLE_ID         NUMBER         NOT NULL REFERENCES ERP_ROLES(ROLE_ID),
    MODULE_CODE     VARCHAR2(30)   NOT NULL, -- 'COMPANY','CONTACT','OPPORTUNITY', etc.
    CAN_VIEW        CHAR(1)        DEFAULT 'N',
    CAN_CREATE      CHAR(1)        DEFAULT 'N',
    CAN_EDIT        CHAR(1)        DEFAULT 'N',
    CAN_DELETE      CHAR(1)        DEFAULT 'N',
    CAN_EXPORT      CHAR(1)        DEFAULT 'N',
    CONSTRAINT UQ_ROLE_MODULE UNIQUE (ROLE_ID, MODULE_CODE)
);

-- Seed roles
INSERT INTO ERP_ROLES (ROLE_NAME, ROLE_DESC) VALUES ('SuperAdmin',   'Full system access');
INSERT INTO ERP_ROLES (ROLE_NAME, ROLE_DESC) VALUES ('Admin',        'Module admin without user management');
INSERT INTO ERP_ROLES (ROLE_NAME, ROLE_DESC) VALUES ('BDManager',    'Business Development Manager');
INSERT INTO ERP_ROLES (ROLE_NAME, ROLE_DESC) VALUES ('Analyst',      'Research & Analytics read/write');
INSERT INTO ERP_ROLES (ROLE_NAME, ROLE_DESC) VALUES ('Viewer',       'Read-only access all modules');
COMMIT;

-- ============================================================
-- MODULE 1 – COMPANY MASTER
-- ============================================================
CREATE TABLE MST_COMPANY (
    COMPANY_ID          NUMBER          DEFAULT SEQ_COMPANY.NEXTVAL PRIMARY KEY,
    COMPANY_NAME        VARCHAR2(200)   NOT NULL,
    COMPANY_TYPE        VARCHAR2(30)    NOT NULL, -- FK to REF_LOOKUP COMPANY_TYPE
    HEADQUARTERS        VARCHAR2(200),
    WEBSITE             VARCHAR2(300),
    INDUSTRY_SEGMENT    VARCHAR2(500),  -- comma-separated multi-segment
    PARENT_COMPANY      VARCHAR2(200),
    EMPLOYEE_COUNT      NUMBER,
    ANNUAL_REVENUE      VARCHAR2(100),  -- stored as text to accommodate ₹/$ + ranges
    REVENUE_YEAR        NUMBER(4),
    MARKET_RANK         NUMBER,
    REVENUE_RANK        NUMBER,
    TECH_RANK           NUMBER,
    GROWTH_RANK         NUMBER,
    FRESHER_RANK        NUMBER,
    CERTIFICATIONS      VARCHAR2(500),
    EXPORT_COUNTRIES    VARCHAR2(500),
    STRATEGIC_PARTNERS  VARCHAR2(1000),
    CAREERS_URL         VARCHAR2(300),
    INTERNSHIP_AVAIL    CHAR(1)         DEFAULT 'N',
    GET_PROGRAM         CHAR(1)         DEFAULT 'N',
    NOTES               CLOB,
    IS_ACTIVE           CHAR(1)         DEFAULT 'Y',
    CREATED_ON          DATE            DEFAULT SYSDATE,
    CREATED_BY          NUMBER,
    UPDATED_ON          DATE,
    UPDATED_BY          NUMBER
);
COMMENT ON TABLE MST_COMPANY IS 'Central company master – all aerospace companies';

CREATE TABLE MST_COMPANY_FACILITIES (
    FACILITY_ID     NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COMPANY_ID      NUMBER          NOT NULL REFERENCES MST_COMPANY(COMPANY_ID) ON DELETE CASCADE,
    FACILITY_NAME   VARCHAR2(200),
    CITY            VARCHAR2(100),
    STATE           VARCHAR2(100),
    COUNTRY         VARCHAR2(100)   DEFAULT 'India',
    FACILITY_TYPE   VARCHAR2(50),   -- 'Headquarters','Manufacturing','R&D','MRO'
    IS_ACTIVE       CHAR(1)         DEFAULT 'Y'
);

CREATE TABLE MST_COMPANY_SEGMENT (
    SEG_ID          NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COMPANY_ID      NUMBER          NOT NULL REFERENCES MST_COMPANY(COMPANY_ID) ON DELETE CASCADE,
    SEGMENT_CODE    VARCHAR2(30)    NOT NULL,
    PRODUCTS_SVCS   VARCHAR2(2000),
    MAJOR_CUSTOMERS VARCHAR2(1000)
);

-- ============================================================
-- MODULE 2 – CONTACT MANAGEMENT
-- ============================================================
CREATE TABLE CRM_CONTACT (
    CONTACT_ID          NUMBER          DEFAULT SEQ_CONTACT.NEXTVAL PRIMARY KEY,
    COMPANY_ID          NUMBER          REFERENCES MST_COMPANY(COMPANY_ID),
    CONTACT_NAME        VARCHAR2(100)   NOT NULL,
    DESIGNATION         VARCHAR2(100),
    DEPARTMENT          VARCHAR2(100),
    EMAIL               VARCHAR2(150),
    MOBILE              VARCHAR2(20),
    LINKEDIN_URL        VARCHAR2(300),
    LOCATION            VARCHAR2(200),
    REPORTING_MANAGER   VARCHAR2(100),
    CONTACT_STATUS      VARCHAR2(30)    DEFAULT 'ACTIVE', -- ACTIVE/INACTIVE/PROSPECT
    LAST_COMM_DATE      DATE,
    NEXT_FOLLOWUP_DATE  DATE,
    NOTES               CLOB,
    IS_ACTIVE           CHAR(1)         DEFAULT 'Y',
    CREATED_ON          DATE            DEFAULT SYSDATE,
    CREATED_BY          NUMBER,
    UPDATED_ON          DATE,
    UPDATED_BY          NUMBER
);
COMMENT ON TABLE CRM_CONTACT IS 'Aerospace industry contact directory';

-- ============================================================
-- MODULE 3 – BUSINESS OPPORTUNITY TRACKER
-- ============================================================
CREATE TABLE BIZ_OPPORTUNITY (
    OPP_ID              NUMBER          DEFAULT SEQ_OPPORTUNITY.NEXTVAL PRIMARY KEY,
    COMPANY_ID          NUMBER          NOT NULL REFERENCES MST_COMPANY(COMPANY_ID),
    CONTACT_ID          NUMBER          REFERENCES CRM_CONTACT(CONTACT_ID),
    OPP_TYPE            VARCHAR2(50),   -- 'RFQ','Tender','Partnership','Direct Sale'
    RFQ_NUMBER          VARCHAR2(100),
    TENDER_NUMBER       VARCHAR2(100),
    PROJECT_NAME        VARCHAR2(300)   NOT NULL,
    OPP_VALUE           NUMBER(15,2),
    CURRENCY            VARCHAR2(5)     DEFAULT 'INR',
    PROBABILITY_PCT     NUMBER(5,2),
    STATUS              VARCHAR2(30)    DEFAULT 'NEW',
    SUBMISSION_DATE     DATE,
    EXPECTED_AWARD_DATE DATE,
    ACTUAL_AWARD_DATE   DATE,
    REMARKS             CLOB,
    ASSIGNED_TO         NUMBER          REFERENCES ERP_USERS(USER_ID),
    IS_ACTIVE           CHAR(1)         DEFAULT 'Y',
    CREATED_ON          DATE            DEFAULT SYSDATE,
    CREATED_BY          NUMBER,
    UPDATED_ON          DATE,
    UPDATED_BY          NUMBER
);
COMMENT ON TABLE BIZ_OPPORTUNITY IS 'Business development pipeline and opportunity tracking';

-- ============================================================
-- MODULE 4 – JOB & CAREER TRACKER
-- ============================================================
CREATE TABLE JOB_POSTING (
    JOB_ID              NUMBER          DEFAULT SEQ_JOB.NEXTVAL PRIMARY KEY,
    COMPANY_ID          NUMBER          NOT NULL REFERENCES MST_COMPANY(COMPANY_ID),
    POSITION_TITLE      VARCHAR2(200)   NOT NULL,
    DEPARTMENT          VARCHAR2(100),
    JOB_LOCATION        VARCHAR2(200),
    EXP_MIN_YEARS       NUMBER(4,1),
    EXP_MAX_YEARS       NUMBER(4,1),
    SALARY_MIN          NUMBER(12,2),
    SALARY_MAX          NUMBER(12,2),
    SALARY_CURRENCY     VARCHAR2(5)     DEFAULT 'INR',
    APPLICATION_URL     VARCHAR2(500),
    CLOSING_DATE        DATE,
    STATUS              VARCHAR2(30)    DEFAULT 'OPEN',
    JOB_TYPE            VARCHAR2(30),   -- 'Fulltime','Intern','Contract','GET','Apprentice'
    SKILLS_REQUIRED     VARCHAR2(1000),
    NOTES               CLOB,
    MY_APP_STATUS       VARCHAR2(30),   -- Personal application tracking
    MY_APP_DATE         DATE,
    MY_APP_NOTES        VARCHAR2(1000),
    IS_ACTIVE           CHAR(1)         DEFAULT 'Y',
    CREATED_ON          DATE            DEFAULT SYSDATE,
    CREATED_BY          NUMBER
);
COMMENT ON TABLE JOB_POSTING IS 'Job openings and personal application status tracker';

-- ============================================================
-- MODULE 5 – TECHNOLOGY TRACKER
-- ============================================================
CREATE TABLE TECH_PROFILE (
    TECH_ID             NUMBER          DEFAULT SEQ_TECHNOLOGY.NEXTVAL PRIMARY KEY,
    COMPANY_ID          NUMBER          NOT NULL REFERENCES MST_COMPANY(COMPANY_ID) ON DELETE CASCADE,
    TECH_AREA           VARCHAR2(200),
    USES_AI             CHAR(1)         DEFAULT 'N',
    AI_DETAILS          VARCHAR2(500),
    USES_ML             CHAR(1)         DEFAULT 'N',
    ML_DETAILS          VARCHAR2(500),
    USES_EMBEDDED       CHAR(1)         DEFAULT 'N',
    EMBEDDED_DETAILS    VARCHAR2(500),
    USES_AERO_SW        CHAR(1)         DEFAULT 'N',
    AERO_SW_DETAILS     VARCHAR2(500),
    USES_AVIONICS       CHAR(1)         DEFAULT 'N',
    AVIONICS_DETAILS    VARCHAR2(500),
    USES_ADDITIVE_MFG   CHAR(1)         DEFAULT 'N',
    ADDITIVE_DETAILS    VARCHAR2(500),
    USES_DIGITAL_TWIN   CHAR(1)         DEFAULT 'N',
    DT_DETAILS          VARCHAR2(500),
    CAD_TOOLS           VARCHAR2(500),
    SIMULATION_TOOLS    VARCHAR2(500),
    PLM_TOOLS           VARCHAR2(500),
    PROGRAMMING_LANGS   VARCHAR2(500),
    CLOUD_PLATFORMS     VARCHAR2(300),
    CERTIFICATIONS_SW   VARCHAR2(500),  -- DO-178C, DO-254 etc.
    NOTES               CLOB,
    UPDATED_ON          DATE            DEFAULT SYSDATE,
    UPDATED_BY          NUMBER
);

-- ============================================================
-- MODULE 6 – SUPPLIER & VENDOR TRACKER
-- ============================================================
CREATE TABLE SUP_SUPPLIER (
    SUPPLIER_ID         NUMBER          DEFAULT SEQ_SUPPLIER.NEXTVAL PRIMARY KEY,
    SUPPLIER_NAME       VARCHAR2(200)   NOT NULL,
    COMPANY_ID          NUMBER          REFERENCES MST_COMPANY(COMPANY_ID), -- if in master
    PRODUCTS_OFFERED    VARCHAR2(1000),
    CERTIFICATIONS      VARCHAR2(500),
    CITY                VARCHAR2(100),
    STATE               VARCHAR2(100),
    COUNTRY             VARCHAR2(100)   DEFAULT 'India',
    CONTACT_PERSON      VARCHAR2(100),
    CONTACT_EMAIL       VARCHAR2(150),
    CONTACT_MOBILE      VARCHAR2(20),
    APPROVAL_STATUS     VARCHAR2(30)    DEFAULT 'PENDING', -- APPROVED/PENDING/REJECTED/SUSPENDED
    AUDIT_STATUS        VARCHAR2(30)    DEFAULT 'PENDING', -- CLEARED/PENDING/FAILED
    LAST_AUDIT_DATE     DATE,
    NEXT_AUDIT_DATE     DATE,
    APPROVED_BY         NUMBER,
    APPROVED_ON         DATE,
    NOTES               CLOB,
    IS_ACTIVE           CHAR(1)         DEFAULT 'Y',
    CREATED_ON          DATE            DEFAULT SYSDATE,
    CREATED_BY          NUMBER
);

-- ============================================================
-- MODULE 7 – PROJECT TRACKER
-- ============================================================
CREATE TABLE PRJ_PROJECT (
    PROJECT_ID          NUMBER          DEFAULT SEQ_PROJECT.NEXTVAL PRIMARY KEY,
    COMPANY_ID          NUMBER          NOT NULL REFERENCES MST_COMPANY(COMPANY_ID),
    PROJECT_NAME        VARCHAR2(300)   NOT NULL,
    PROJECT_SECTOR      VARCHAR2(30),   -- DEFENCE/COMMERCIAL/SPACE/UAV
    CUSTOMER_SEGMENT    VARCHAR2(100),
    START_DATE          DATE,
    COMPLETION_DATE     DATE,
    PROJECT_VALUE       NUMBER(15,2),
    VALUE_CURRENCY      VARCHAR2(5)     DEFAULT 'INR',
    STATUS              VARCHAR2(30)    DEFAULT 'ONGOING', -- PLANNED/ONGOING/COMPLETED/CANCELLED
    KEY_TECHNOLOGIES    VARCHAR2(1000),
    MILESTONE_1         VARCHAR2(300),
    MILESTONE_1_DATE    DATE,
    MILESTONE_2         VARCHAR2(300),
    MILESTONE_2_DATE    DATE,
    MILESTONE_3         VARCHAR2(300),
    MILESTONE_3_DATE    DATE,
    NOTES               CLOB,
    IS_ACTIVE           CHAR(1)         DEFAULT 'Y',
    CREATED_ON          DATE            DEFAULT SYSDATE,
    CREATED_BY          NUMBER,
    UPDATED_ON          DATE,
    UPDATED_BY          NUMBER
);

-- ============================================================
-- MODULE 8 – DOCUMENT MANAGEMENT
-- ============================================================
CREATE TABLE DOC_DOCUMENT (
    DOC_ID              NUMBER          DEFAULT SEQ_DOCUMENT.NEXTVAL PRIMARY KEY,
    COMPANY_ID          NUMBER          REFERENCES MST_COMPANY(COMPANY_ID),
    CONTACT_ID          NUMBER          REFERENCES CRM_CONTACT(CONTACT_ID),
    OPP_ID              NUMBER          REFERENCES BIZ_OPPORTUNITY(OPP_ID),
    DOC_TYPE            VARCHAR2(50)    NOT NULL, -- 'Brochure','Annual Report','Cert','NDA','Drawing','Presentation','Catalog'
    DOC_TITLE           VARCHAR2(300)   NOT NULL,
    FILE_NAME           VARCHAR2(300),
    FILE_PATH           VARCHAR2(1000),
    FILE_SIZE_KB        NUMBER,
    MIME_TYPE           VARCHAR2(100),
    VERSION             VARCHAR2(20),
    EXPIRY_DATE         DATE,
    IS_CONFIDENTIAL     CHAR(1)         DEFAULT 'N',
    UPLOADED_ON         DATE            DEFAULT SYSDATE,
    UPLOADED_BY         NUMBER,
    NOTES               VARCHAR2(500)
);

-- ============================================================
-- MODULE 9 – CRM & FOLLOW-UP MANAGEMENT
-- ============================================================
CREATE TABLE CRM_ACTIVITY (
    ACTIVITY_ID         NUMBER          DEFAULT SEQ_CRM_ACTIVITY.NEXTVAL PRIMARY KEY,
    COMPANY_ID          NUMBER          REFERENCES MST_COMPANY(COMPANY_ID),
    CONTACT_ID          NUMBER          REFERENCES CRM_CONTACT(CONTACT_ID),
    OPP_ID              NUMBER          REFERENCES BIZ_OPPORTUNITY(OPP_ID),
    ACTIVITY_TYPE       VARCHAR2(30)    NOT NULL, -- 'CALL','MEETING','EMAIL','VISIT','FOLLOWUP','NOTE'
    SUBJECT             VARCHAR2(300)   NOT NULL,
    ACTIVITY_DATE       DATE            NOT NULL,
    DURATION_MINS       NUMBER,
    DESCRIPTION         CLOB,
    OUTCOME             VARCHAR2(500),
    NEXT_ACTION         VARCHAR2(500),
    NEXT_ACTION_DATE    DATE,
    REMINDER_DATE       TIMESTAMP,
    REMINDER_SENT       CHAR(1)         DEFAULT 'N',
    ASSIGNED_TO         NUMBER          REFERENCES ERP_USERS(USER_ID),
    STATUS              VARCHAR2(20)    DEFAULT 'OPEN', -- OPEN/COMPLETED/CANCELLED
    CREATED_ON          DATE            DEFAULT SYSDATE,
    CREATED_BY          NUMBER
);

-- ============================================================
-- AUDIT LOG
-- ============================================================
CREATE TABLE AUD_LOG (
    LOG_ID              NUMBER          DEFAULT SEQ_AUDIT.NEXTVAL PRIMARY KEY,
    TABLE_NAME          VARCHAR2(50),
    RECORD_ID           NUMBER,
    ACTION              VARCHAR2(10),   -- INSERT/UPDATE/DELETE
    OLD_VALUES          CLOB,
    NEW_VALUES          CLOB,
    CHANGED_BY          NUMBER,
    CHANGED_ON          TIMESTAMP       DEFAULT SYSTIMESTAMP,
    IP_ADDRESS          VARCHAR2(50),
    SESSION_ID          VARCHAR2(100)
);

-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX IDX_COMPANY_NAME    ON MST_COMPANY(COMPANY_NAME);
CREATE INDEX IDX_COMPANY_TYPE    ON MST_COMPANY(COMPANY_TYPE);
CREATE INDEX IDX_COMPANY_ACTIVE  ON MST_COMPANY(IS_ACTIVE);
CREATE INDEX IDX_CONTACT_COMPANY ON CRM_CONTACT(COMPANY_ID);
CREATE INDEX IDX_CONTACT_STATUS  ON CRM_CONTACT(CONTACT_STATUS);
CREATE INDEX IDX_OPP_COMPANY     ON BIZ_OPPORTUNITY(COMPANY_ID);
CREATE INDEX IDX_OPP_STATUS      ON BIZ_OPPORTUNITY(STATUS);
CREATE INDEX IDX_JOB_COMPANY     ON JOB_POSTING(COMPANY_ID);
CREATE INDEX IDX_JOB_STATUS      ON JOB_POSTING(STATUS);
CREATE INDEX IDX_TECH_COMPANY    ON TECH_PROFILE(COMPANY_ID);
CREATE INDEX IDX_PRJ_COMPANY     ON PRJ_PROJECT(COMPANY_ID);
CREATE INDEX IDX_DOC_COMPANY     ON DOC_DOCUMENT(COMPANY_ID);
CREATE INDEX IDX_CRM_COMPANY     ON CRM_ACTIVITY(COMPANY_ID);
CREATE INDEX IDX_CRM_DATE        ON CRM_ACTIVITY(ACTIVITY_DATE);
CREATE INDEX IDX_CRM_REMINDER    ON CRM_ACTIVITY(REMINDER_DATE);
CREATE INDEX IDX_USER_EMAIL      ON ERP_USERS(EMAIL);

-- ============================================================
-- VIEWS
-- ============================================================
CREATE OR REPLACE VIEW V_COMPANY_FULL AS
SELECT
    c.COMPANY_ID, c.COMPANY_NAME, c.COMPANY_TYPE, c.HEADQUARTERS,
    c.WEBSITE, c.INDUSTRY_SEGMENT, c.ANNUAL_REVENUE, c.EMPLOYEE_COUNT,
    c.CERTIFICATIONS, c.EXPORT_COUNTRIES, c.CAREERS_URL,
    c.INTERNSHIP_AVAIL, c.GET_PROGRAM, c.IS_ACTIVE,
    (SELECT COUNT(*) FROM CRM_CONTACT cc WHERE cc.COMPANY_ID = c.COMPANY_ID AND cc.IS_ACTIVE='Y') AS CONTACT_COUNT,
    (SELECT COUNT(*) FROM BIZ_OPPORTUNITY bo WHERE bo.COMPANY_ID = c.COMPANY_ID AND bo.IS_ACTIVE='Y') AS OPP_COUNT,
    (SELECT COUNT(*) FROM JOB_POSTING jp WHERE jp.COMPANY_ID = c.COMPANY_ID AND jp.STATUS='OPEN') AS OPEN_JOBS,
    (SELECT COUNT(*) FROM PRJ_PROJECT pp WHERE pp.COMPANY_ID = c.COMPANY_ID AND pp.STATUS='ONGOING') AS ACTIVE_PROJECTS,
    tp.USES_AI, tp.USES_ML, tp.USES_DIGITAL_TWIN, tp.CAD_TOOLS
FROM MST_COMPANY c
LEFT JOIN TECH_PROFILE tp ON tp.COMPANY_ID = c.COMPANY_ID
WHERE c.IS_ACTIVE = 'Y';

CREATE OR REPLACE VIEW V_DASHBOARD_KPI AS
SELECT
    (SELECT COUNT(*) FROM MST_COMPANY WHERE IS_ACTIVE='Y') AS TOTAL_COMPANIES,
    (SELECT COUNT(*) FROM MST_COMPANY WHERE IS_ACTIVE='Y' AND INDUSTRY_SEGMENT LIKE '%DEFENCE%') AS DEFENCE_COMPANIES,
    (SELECT COUNT(*) FROM MST_COMPANY WHERE IS_ACTIVE='Y' AND INDUSTRY_SEGMENT LIKE '%SPACE%') AS SPACE_COMPANIES,
    (SELECT COUNT(*) FROM MST_COMPANY WHERE IS_ACTIVE='Y' AND INDUSTRY_SEGMENT LIKE '%UAV%') AS DRONE_COMPANIES,
    (SELECT COUNT(*) FROM CRM_CONTACT WHERE IS_ACTIVE='Y') AS TOTAL_CONTACTS,
    (SELECT COUNT(*) FROM BIZ_OPPORTUNITY WHERE IS_ACTIVE='Y' AND STATUS NOT IN ('WON','LOST')) AS ACTIVE_OPPS,
    (SELECT NVL(SUM(OPP_VALUE),0) FROM BIZ_OPPORTUNITY WHERE IS_ACTIVE='Y' AND STATUS NOT IN ('WON','LOST')) AS PIPELINE_VALUE,
    (SELECT COUNT(*) FROM JOB_POSTING WHERE STATUS='OPEN') AS OPEN_JOBS,
    (SELECT COUNT(*) FROM CRM_ACTIVITY WHERE STATUS='OPEN' AND ACTIVITY_DATE <= SYSDATE+7) AS UPCOMING_FOLLOWUPS,
    (SELECT COUNT(*) FROM TECH_PROFILE WHERE USES_AI='Y') AS AI_COMPANIES
FROM DUAL;

COMMIT;
