-- ================================================================
-- AeroERP — Seed Data for all modules (Oracle SQL)
-- Run AFTER 01_schema_ddl.sql
-- ================================================================

-- ── SEED USERS (password = BCrypt of "Aero@2025") ────────────
INSERT INTO ERP_USERS (USER_ID, USERNAME, EMAIL, PASSWORD_HASH, FULL_NAME, MOBILE, ROLE_ID, IS_ACTIVE)
VALUES (SEQ_USER.NEXTVAL, 'admin', 'admin@aeroerp.in',
  '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TiRXpPMV.5G0pJXfmTv8XqPFWY6m', -- Aero@2025
  'System Admin', '+91-00000-00000',
  (SELECT ROLE_ID FROM ERP_ROLES WHERE ROLE_NAME='SuperAdmin'), 'Y');

INSERT INTO ERP_USERS (USER_ID, USERNAME, EMAIL, PASSWORD_HASH, FULL_NAME, MOBILE, ROLE_ID, IS_ACTIVE)
VALUES (SEQ_USER.NEXTVAL, 'mahin', 'mahin@aeroerp.in',
  '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TiRXpPMV.5G0pJXfmTv8XqPFWY6m',
  'Mahin', '+91-00000-00001',
  (SELECT ROLE_ID FROM ERP_ROLES WHERE ROLE_NAME='Analyst'), 'Y');

-- ── MODULE PERMISSIONS FOR ALL ROLES ─────────────────────────
-- SuperAdmin: all CRUD+Export on all modules
BEGIN
  FOR m IN (SELECT COLUMN_VALUE AS MC FROM TABLE(SYS.ODCIVARCHAR2LIST(
    'COMPANY','CONTACT','OPPORTUNITY','JOB','TECHNOLOGY','SUPPLIER','PROJECT',
    'DOCUMENT','CRM_ACTIVITY','DASHBOARD','REPORTS','USERS','SETTINGS'))) LOOP
    INSERT INTO ERP_MODULE_PERMISSIONS (ROLE_ID, MODULE_CODE, CAN_VIEW, CAN_CREATE, CAN_EDIT, CAN_DELETE, CAN_EXPORT)
    VALUES ((SELECT ROLE_ID FROM ERP_ROLES WHERE ROLE_NAME='SuperAdmin'),
            m.MC, 'Y','Y','Y','Y','Y');
  END LOOP;
END;
/

-- Analyst: CRUD on Company/Contact/Job/Tech, view on Opp/Project
BEGIN
  FOR m IN (SELECT COLUMN_VALUE AS MC FROM TABLE(SYS.ODCIVARCHAR2LIST(
    'COMPANY','CONTACT','JOB','TECHNOLOGY','CRM_ACTIVITY','REPORTS','DASHBOARD'))) LOOP
    INSERT INTO ERP_MODULE_PERMISSIONS (ROLE_ID, MODULE_CODE, CAN_VIEW, CAN_CREATE, CAN_EDIT, CAN_DELETE, CAN_EXPORT)
    VALUES ((SELECT ROLE_ID FROM ERP_ROLES WHERE ROLE_NAME='Analyst'),
            m.MC, 'Y','Y','Y','N','Y');
  END LOOP;
  FOR m IN (SELECT COLUMN_VALUE AS MC FROM TABLE(SYS.ODCIVARCHAR2LIST(
    'OPPORTUNITY','PROJECT','SUPPLIER','DOCUMENT'))) LOOP
    INSERT INTO ERP_MODULE_PERMISSIONS (ROLE_ID, MODULE_CODE, CAN_VIEW, CAN_CREATE, CAN_EDIT, CAN_DELETE, CAN_EXPORT)
    VALUES ((SELECT ROLE_ID FROM ERP_ROLES WHERE ROLE_NAME='Analyst'),
            m.MC, 'Y','N','N','N','N');
  END LOOP;
END;
/

-- Viewer: view-only all modules
BEGIN
  FOR m IN (SELECT COLUMN_VALUE AS MC FROM TABLE(SYS.ODCIVARCHAR2LIST(
    'COMPANY','CONTACT','OPPORTUNITY','JOB','TECHNOLOGY','SUPPLIER','PROJECT',
    'DOCUMENT','CRM_ACTIVITY','DASHBOARD','REPORTS'))) LOOP
    INSERT INTO ERP_MODULE_PERMISSIONS (ROLE_ID, MODULE_CODE, CAN_VIEW, CAN_CREATE, CAN_EDIT, CAN_DELETE, CAN_EXPORT)
    VALUES ((SELECT ROLE_ID FROM ERP_ROLES WHERE ROLE_NAME='Viewer'),
            m.MC, 'Y','N','N','N','N');
  END LOOP;
END;
/

-- ── MODULE 1: COMPANY MASTER SEED ────────────────────────────
INSERT INTO MST_COMPANY (COMPANY_ID,COMPANY_NAME,COMPANY_TYPE,HEADQUARTERS,WEBSITE,INDUSTRY_SEGMENT,EMPLOYEE_COUNT,ANNUAL_REVENUE,REVENUE_YEAR,CERTIFICATIONS,CAREERS_URL,GET_PROGRAM,INTERNSHIP_AVAIL)
VALUES (SEQ_COMPANY.NEXTVAL,'Hindustan Aeronautics Limited','PSU','Bangalore, Karnataka','https://hal-india.co.in','DEFENCE,MFG,AVIONICS',30000,'₹28,162 Cr',2024,'AS9100D,CMMI L5,ISO 9001','https://hal-india.co.in/careers','Y','Y');

INSERT INTO MST_COMPANY (COMPANY_ID,COMPANY_NAME,COMPANY_TYPE,HEADQUARTERS,WEBSITE,INDUSTRY_SEGMENT,EMPLOYEE_COUNT,ANNUAL_REVENUE,REVENUE_YEAR,CERTIFICATIONS,CAREERS_URL,GET_PROGRAM,INTERNSHIP_AVAIL)
VALUES (SEQ_COMPANY.NEXTVAL,'Bharat Electronics Limited','PSU','Bangalore, Karnataka','https://bel-india.in','AVIONICS,DEFENCE',12400,'₹19,996 Cr',2024,'AS9100D,ISO 9001,ISO 27001','https://bel-india.in/careers','Y','Y');

INSERT INTO MST_COMPANY (COMPANY_ID,COMPANY_NAME,COMPANY_TYPE,HEADQUARTERS,WEBSITE,INDUSTRY_SEGMENT,EMPLOYEE_COUNT,ANNUAL_REVENUE,REVENUE_YEAR,CERTIFICATIONS,CAREERS_URL,GET_PROGRAM,INTERNSHIP_AVAIL)
VALUES (SEQ_COMPANY.NEXTVAL,'ISRO','Govt.','Bangalore, Karnataka','https://isro.gov.in','SPACE',17000,'₹13,043 Cr',2024,'ISO 9001','https://isro.gov.in/careers','Y','Y');

INSERT INTO MST_COMPANY (COMPANY_ID,COMPANY_NAME,COMPANY_TYPE,HEADQUARTERS,WEBSITE,INDUSTRY_SEGMENT,EMPLOYEE_COUNT,ANNUAL_REVENUE,REVENUE_YEAR,CERTIFICATIONS,CAREERS_URL,GET_PROGRAM,INTERNSHIP_AVAIL)
VALUES (SEQ_COMPANY.NEXTVAL,'DRDO','Govt.','New Delhi','https://drdo.gov.in','DEFENCE',30000,'₹23,264 Cr',2024,'ISO 9001','https://drdo.gov.in/careers','Y','Y');

INSERT INTO MST_COMPANY (COMPANY_ID,COMPANY_NAME,COMPANY_TYPE,HEADQUARTERS,WEBSITE,INDUSTRY_SEGMENT,EMPLOYEE_COUNT,ANNUAL_REVENUE,REVENUE_YEAR,CERTIFICATIONS,CAREERS_URL,GET_PROGRAM,INTERNSHIP_AVAIL)
VALUES (SEQ_COMPANY.NEXTVAL,'Honeywell Aerospace India','MNC','Hyderabad, Telangana','https://aerospace.honeywell.com','AVIONICS,SOFTWARE',18000,'₹8,000 Cr',2024,'AS9100D,DO-178C,ISO 9001','https://careers.honeywell.com','Y','Y');

INSERT INTO MST_COMPANY (COMPANY_ID,COMPANY_NAME,COMPANY_TYPE,HEADQUARTERS,WEBSITE,INDUSTRY_SEGMENT,EMPLOYEE_COUNT,ANNUAL_REVENUE,REVENUE_YEAR,CERTIFICATIONS,CAREERS_URL,GET_PROGRAM,INTERNSHIP_AVAIL)
VALUES (SEQ_COMPANY.NEXTVAL,'GE Aerospace India','MNC','Hyderabad, Telangana','https://www.geaerospace.com','SOFTWARE,AVIONICS',10000,'₹6,000 Cr',2024,'AS9100D,DO-178C,ISO 9001','https://jobs.geaerospace.com','Y','Y');

INSERT INTO MST_COMPANY (COMPANY_ID,COMPANY_NAME,COMPANY_TYPE,HEADQUARTERS,WEBSITE,INDUSTRY_SEGMENT,EMPLOYEE_COUNT,ANNUAL_REVENUE,REVENUE_YEAR,CERTIFICATIONS,CAREERS_URL,GET_PROGRAM,INTERNSHIP_AVAIL)
VALUES (SEQ_COMPANY.NEXTVAL,'Cyient Limited','Private','Hyderabad, Telangana','https://cyient.com','SOFTWARE,AVIONICS,MRO',15000,'₹7,200 Cr',2024,'AS9100D,DO-178C,CMMI L5','https://cyient.com/careers','Y','Y');

INSERT INTO MST_COMPANY (COMPANY_ID,COMPANY_NAME,COMPANY_TYPE,HEADQUARTERS,WEBSITE,INDUSTRY_SEGMENT,EMPLOYEE_COUNT,ANNUAL_REVENUE,REVENUE_YEAR,CERTIFICATIONS,CAREERS_URL,GET_PROGRAM,INTERNSHIP_AVAIL)
VALUES (SEQ_COMPANY.NEXTVAL,'Tata Advanced Systems Limited','Private','Hyderabad, Telangana','https://tataadvancedsystems.com','MFG,DEFENCE',2500,'₹3,500 Cr',2024,'AS9100D,ISO 9001,NADCAP','https://tataadvancedsystems.com/careers','Y','Y');

INSERT INTO MST_COMPANY (COMPANY_ID,COMPANY_NAME,COMPANY_TYPE,HEADQUARTERS,WEBSITE,INDUSTRY_SEGMENT,EMPLOYEE_COUNT,ANNUAL_REVENUE,REVENUE_YEAR,CERTIFICATIONS,CAREERS_URL,GET_PROGRAM,INTERNSHIP_AVAIL)
VALUES (SEQ_COMPANY.NEXTVAL,'Collins Aerospace India','MNC','Hyderabad, Telangana','https://collinsaerospace.com','AVIONICS,MFG',6000,'₹4,500 Cr',2024,'AS9100D,DO-178C,NADCAP','https://jobs.collinsaerospace.com','Y','Y');

INSERT INTO MST_COMPANY (COMPANY_ID,COMPANY_NAME,COMPANY_TYPE,HEADQUARTERS,WEBSITE,INDUSTRY_SEGMENT,EMPLOYEE_COUNT,ANNUAL_REVENUE,REVENUE_YEAR,CERTIFICATIONS,CAREERS_URL,GET_PROGRAM,INTERNSHIP_AVAIL)
VALUES (SEQ_COMPANY.NEXTVAL,'ideaForge Technology','Private','Mumbai, Maharashtra','https://ideaforge.in','UAV',400,'₹355 Cr',2024,'NPNT,DGCA Certified','https://ideaforge.in/careers','N','Y');

INSERT INTO MST_COMPANY (COMPANY_ID,COMPANY_NAME,COMPANY_TYPE,HEADQUARTERS,WEBSITE,INDUSTRY_SEGMENT,EMPLOYEE_COUNT,ANNUAL_REVENUE,REVENUE_YEAR,CERTIFICATIONS,CAREERS_URL,GET_PROGRAM,INTERNSHIP_AVAIL)
VALUES (SEQ_COMPANY.NEXTVAL,'Skyroot Aerospace','Startup','Hyderabad, Telangana','https://skyroot.in','SPACE',250,'$51Mn raised',2024,'IN-SPACe Approved','https://skyroot.in/careers','N','Y');

INSERT INTO MST_COMPANY (COMPANY_ID,COMPANY_NAME,COMPANY_TYPE,HEADQUARTERS,WEBSITE,INDUSTRY_SEGMENT,EMPLOYEE_COUNT,ANNUAL_REVENUE,REVENUE_YEAR,CERTIFICATIONS,CAREERS_URL,GET_PROGRAM,INTERNSHIP_AVAIL)
VALUES (SEQ_COMPANY.NEXTVAL,'Agnikul Cosmos','Startup','Chennai, Tamil Nadu','https://agnikul.in','SPACE',150,'$27Mn raised',2024,'IN-SPACe Approved','https://agnikul.in/careers','N','Y');

INSERT INTO MST_COMPANY (COMPANY_ID,COMPANY_NAME,COMPANY_TYPE,HEADQUARTERS,WEBSITE,INDUSTRY_SEGMENT,EMPLOYEE_COUNT,ANNUAL_REVENUE,REVENUE_YEAR,CERTIFICATIONS,CAREERS_URL,GET_PROGRAM,INTERNSHIP_AVAIL)
VALUES (SEQ_COMPANY.NEXTVAL,'Pixxel Space','Startup','Bangalore, Karnataka','https://pixxel.space','SPACE',150,'$71Mn raised',2024,'IN-SPACe Approved','https://pixxel.space/careers','N','Y');

INSERT INTO MST_COMPANY (COMPANY_ID,COMPANY_NAME,COMPANY_TYPE,HEADQUARTERS,WEBSITE,INDUSTRY_SEGMENT,EMPLOYEE_COUNT,ANNUAL_REVENUE,REVENUE_YEAR,CERTIFICATIONS,CAREERS_URL,GET_PROGRAM,INTERNSHIP_AVAIL)
VALUES (SEQ_COMPANY.NEXTVAL,'Garuda Aerospace','Startup','Chennai, Tamil Nadu','https://garudaaerospace.com','UAV',350,'₹150 Cr',2024,'DGCA Approved,NPNT','https://garudaaerospace.com/careers','N','Y');

INSERT INTO MST_COMPANY (COMPANY_ID,COMPANY_NAME,COMPANY_TYPE,HEADQUARTERS,WEBSITE,INDUSTRY_SEGMENT,EMPLOYEE_COUNT,ANNUAL_REVENUE,REVENUE_YEAR,CERTIFICATIONS,CAREERS_URL,GET_PROGRAM,INTERNSHIP_AVAIL)
VALUES (SEQ_COMPANY.NEXTVAL,'Astra Microwave Products','Private','Hyderabad, Telangana','https://astramwp.com','AVIONICS,DEFENCE',700,'₹630 Cr',2024,'AS9100D,ISO 9001','https://astramwp.com/careers','Y','Y');

INSERT INTO MST_COMPANY (COMPANY_ID,COMPANY_NAME,COMPANY_TYPE,HEADQUARTERS,WEBSITE,INDUSTRY_SEGMENT,EMPLOYEE_COUNT,ANNUAL_REVENUE,REVENUE_YEAR,CERTIFICATIONS,CAREERS_URL,GET_PROGRAM,INTERNSHIP_AVAIL)
VALUES (SEQ_COMPANY.NEXTVAL,'Bharat Dynamics Limited','PSU','Hyderabad, Telangana','https://bdl-india.in','DEFENCE',4500,'₹4,898 Cr',2024,'ISO 9001,AS9100D','https://bdl-india.in/careers','Y','Y');

INSERT INTO MST_COMPANY (COMPANY_ID,COMPANY_NAME,COMPANY_TYPE,HEADQUARTERS,WEBSITE,INDUSTRY_SEGMENT,EMPLOYEE_COUNT,ANNUAL_REVENUE,REVENUE_YEAR,CERTIFICATIONS,CAREERS_URL,GET_PROGRAM,INTERNSHIP_AVAIL)
VALUES (SEQ_COMPANY.NEXTVAL,'KPIT Technologies','Private','Pune, Maharashtra','https://kpit.com','SOFTWARE',13000,'₹5,200 Cr',2024,'CMMI L5,ISO 9001','https://kpit.com/careers','Y','Y');

INSERT INTO MST_COMPANY (COMPANY_ID,COMPANY_NAME,COMPANY_TYPE,HEADQUARTERS,WEBSITE,INDUSTRY_SEGMENT,EMPLOYEE_COUNT,ANNUAL_REVENUE,REVENUE_YEAR,CERTIFICATIONS,CAREERS_URL,GET_PROGRAM,INTERNSHIP_AVAIL)
VALUES (SEQ_COMPANY.NEXTVAL,'Wipro Aerospace','Private','Bangalore, Karnataka','https://wipro.com','SOFTWARE,MRO',3000,'₹2,500 Cr',2024,'AS9100D,DO-178C','https://careers.wipro.com','Y','Y');

INSERT INTO MST_COMPANY (COMPANY_ID,COMPANY_NAME,COMPANY_TYPE,HEADQUARTERS,WEBSITE,INDUSTRY_SEGMENT,EMPLOYEE_COUNT,ANNUAL_REVENUE,REVENUE_YEAR,CERTIFICATIONS,CAREERS_URL,GET_PROGRAM,INTERNSHIP_AVAIL)
VALUES (SEQ_COMPANY.NEXTVAL,'Thales India','MNC','Delhi NCR','https://thalesgroup.com/india','AVIONICS,DEFENCE',2000,'₹3,000 Cr',2024,'AS9100D,ISO 9001','https://thalesgroup.com/careers','Y','Y');

INSERT INTO MST_COMPANY (COMPANY_ID,COMPANY_NAME,COMPANY_TYPE,HEADQUARTERS,WEBSITE,INDUSTRY_SEGMENT,EMPLOYEE_COUNT,ANNUAL_REVENUE,REVENUE_YEAR,CERTIFICATIONS,CAREERS_URL,GET_PROGRAM,INTERNSHIP_AVAIL)
VALUES (SEQ_COMPANY.NEXTVAL,'Rolls-Royce India','MNC','Bangalore, Karnataka','https://rollsroyce.com','SOFTWARE,MFG',1000,'₹2,500 Cr',2024,'AS9100D,CMMI L3','https://careers.rolls-royce.com','Y','Y');

-- ── MODULE 5: TECH PROFILES ───────────────────────────────────
-- HAL
INSERT INTO TECH_PROFILE (TECH_ID,COMPANY_ID,USES_AI,AI_DETAILS,USES_ML,USES_EMBEDDED,USES_AERO_SW,USES_AVIONICS,USES_DIGITAL_TWIN,USES_ADDITIVE_MFG,CAD_TOOLS,SIMULATION_TOOLS,PROGRAMMING_LANGS,CERTIFICATIONS_SW)
VALUES (SEQ_TECHNOLOGY.NEXTVAL,
  (SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%Hindustan%' AND ROWNUM=1),
  'Y','Predictive maintenance, quality AI','Y','Y','Y','Y','Y','Y',
  'CATIA V5,Siemens NX,DELMIA','ANSYS Fluent,MATLAB,NASTRAN','C,C++,Ada,MATLAB,Python','DO-178C,DO-254');

-- BEL
INSERT INTO TECH_PROFILE (TECH_ID,COMPANY_ID,USES_AI,AI_DETAILS,USES_ML,USES_EMBEDDED,USES_AERO_SW,USES_AVIONICS,USES_DIGITAL_TWIN,USES_ADDITIVE_MFG,CAD_TOOLS,SIMULATION_TOOLS,PROGRAMMING_LANGS,CERTIFICATIONS_SW)
VALUES (SEQ_TECHNOLOGY.NEXTVAL,
  (SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%Bharat Electronics%' AND ROWNUM=1),
  'Y','Radar signal processing AI','Y','Y','Y','Y','N','N',
  'Cadence,Mentor EDA','CST Studio,MATLAB,ModelSim','C,C++,VHDL,Verilog,Python','DO-254,DO-178C');

-- Honeywell
INSERT INTO TECH_PROFILE (TECH_ID,COMPANY_ID,USES_AI,AI_DETAILS,USES_ML,USES_EMBEDDED,USES_AERO_SW,USES_AVIONICS,USES_DIGITAL_TWIN,USES_ADDITIVE_MFG,CAD_TOOLS,SIMULATION_TOOLS,PROGRAMMING_LANGS,CERTIFICATIONS_SW)
VALUES (SEQ_TECHNOLOGY.NEXTVAL,
  (SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%Honeywell%' AND ROWNUM=1),
  'Y','Predictive MRO, Crew AI, Forge EAM','Y','Y','Y','Y','Y','Y',
  'CATIA,NX,Creo','ANSYS,Fluent,Altair','Python,C++,Ada,Java','DO-178C,DO-254,CMMI L5');

-- ideaForge
INSERT INTO TECH_PROFILE (TECH_ID,COMPANY_ID,USES_AI,AI_DETAILS,USES_ML,USES_EMBEDDED,USES_AERO_SW,USES_AVIONICS,USES_DIGITAL_TWIN,USES_ADDITIVE_MFG,CAD_TOOLS,SIMULATION_TOOLS,PROGRAMMING_LANGS,CERTIFICATIONS_SW)
VALUES (SEQ_TECHNOLOGY.NEXTVAL,
  (SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%ideaForge%' AND ROWNUM=1),
  'Y','Object detection YOLO,target tracking','Y','Y','N','N','N','Y',
  'SolidWorks,Fusion 360','MATLAB/Simulink,ROS','Python,C++,ROS,OpenCV','NPNT');

-- Skyroot
INSERT INTO TECH_PROFILE (TECH_ID,COMPANY_ID,USES_AI,AI_DETAILS,USES_ML,USES_EMBEDDED,USES_AERO_SW,USES_AVIONICS,USES_DIGITAL_TWIN,USES_ADDITIVE_MFG,CAD_TOOLS,SIMULATION_TOOLS,PROGRAMMING_LANGS,CERTIFICATIONS_SW)
VALUES (SEQ_TECHNOLOGY.NEXTVAL,
  (SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%Skyroot%' AND ROWNUM=1),
  'Y','Trajectory optimization ML','Y','Y','Y','Y','Y','Y',
  'CATIA,Fusion 360','OpenFOAM,MATLAB,RocketCEA','Python,C++,MATLAB,Julia','IN-SPACe');

-- Pixxel
INSERT INTO TECH_PROFILE (TECH_ID,COMPANY_ID,USES_AI,AI_DETAILS,USES_ML,USES_EMBEDDED,USES_AERO_SW,USES_AVIONICS,USES_DIGITAL_TWIN,USES_ADDITIVE_MFG,CAD_TOOLS,SIMULATION_TOOLS,PROGRAMMING_LANGS,CERTIFICATIONS_SW)
VALUES (SEQ_TECHNOLOGY.NEXTVAL,
  (SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%Pixxel%' AND ROWNUM=1),
  'Y','Hyperspectral AI crop health, fire detection','Y','Y','Y','N','N','Y',
  'SolidWorks,FreeCAD','GMAT,OpenFOAM','Python,TF,PyTorch,OpenCV','IN-SPACe');

-- ── MODULE 2: SAMPLE CONTACTS ─────────────────────────────────
INSERT INTO CRM_CONTACT (CONTACT_ID,COMPANY_ID,CONTACT_NAME,DESIGNATION,DEPARTMENT,EMAIL,MOBILE,LOCATION,CONTACT_STATUS)
VALUES (SEQ_CONTACT.NEXTVAL,
  (SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%Hindustan%' AND ROWNUM=1),
  'Anita Sharma','Senior HR Manager','Human Resources','anita.s@hal-india.co.in','+91-80-2232-0101','Bangalore','ACTIVE');

INSERT INTO CRM_CONTACT (CONTACT_ID,COMPANY_ID,CONTACT_NAME,DESIGNATION,DEPARTMENT,EMAIL,MOBILE,LOCATION,CONTACT_STATUS)
VALUES (SEQ_CONTACT.NEXTVAL,
  (SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%Bharat Electronics%' AND ROWNUM=1),
  'Mohan Rao','GM Business Development','BD & Marketing','mohan.r@bel-india.in','+91-80-2296-3141','Bangalore','ACTIVE');

INSERT INTO CRM_CONTACT (CONTACT_ID,COMPANY_ID,CONTACT_NAME,DESIGNATION,DEPARTMENT,EMAIL,MOBILE,LOCATION,CONTACT_STATUS)
VALUES (SEQ_CONTACT.NEXTVAL,
  (SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%Cyient%' AND ROWNUM=1),
  'Priya Nair','Talent Acquisition Lead','HR & Talent','priya.n@cyient.com','+91-40-6764-1000','Hyderabad','ACTIVE');

-- ── MODULE 3: SAMPLE OPPORTUNITIES ───────────────────────────
INSERT INTO BIZ_OPPORTUNITY (OPP_ID,COMPANY_ID,OPP_TYPE,RFQ_NUMBER,PROJECT_NAME,OPP_VALUE,CURRENCY,PROBABILITY_PCT,STATUS,SUBMISSION_DATE,EXPECTED_AWARD_DATE)
VALUES (SEQ_OPPORTUNITY.NEXTVAL,
  (SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%Hindustan%' AND ROWNUM=1),
  'RFQ','RFQ-24-HAL-0188','Tejas Mk1A Avionics Software Module',450000000,'INR',65,'QUALIFIED',
  DATE '2025-07-15', DATE '2025-09-30');

INSERT INTO BIZ_OPPORTUNITY (OPP_ID,COMPANY_ID,OPP_TYPE,TENDER_NUMBER,PROJECT_NAME,OPP_VALUE,CURRENCY,PROBABILITY_PCT,STATUS,SUBMISSION_DATE,EXPECTED_AWARD_DATE)
VALUES (SEQ_OPPORTUNITY.NEXTVAL,
  (SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%Bharat Electronics%' AND ROWNUM=1),
  'Tender','BEL-T-0923','BEL AESA Radar Signal Processing Module',3100000000,'INR',55,'PROPOSAL',
  DATE '2025-06-25', DATE '2025-10-15');

INSERT INTO BIZ_OPPORTUNITY (OPP_ID,COMPANY_ID,OPP_TYPE,PROJECT_NAME,OPP_VALUE,CURRENCY,PROBABILITY_PCT,STATUS,SUBMISSION_DATE)
VALUES (SEQ_OPPORTUNITY.NEXTVAL,
  (SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%DRDO%' AND ROWNUM=1),
  'Direct Sale','DRDO EW Sub-system Supply',1200000000,'INR',45,'NEW',DATE '2025-08-01');

-- ── MODULE 4: SAMPLE JOBS ─────────────────────────────────────
INSERT INTO JOB_POSTING (JOB_ID,COMPANY_ID,POSITION_TITLE,DEPARTMENT,JOB_LOCATION,EXP_MIN_YEARS,EXP_MAX_YEARS,SALARY_MIN,SALARY_MAX,APPLICATION_URL,CLOSING_DATE,STATUS,JOB_TYPE,SKILLS_REQUIRED)
VALUES (SEQ_JOB.NEXTVAL,
  (SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%Hindustan%' AND ROWNUM=1),
  'Junior Works Manager – Avionics Division','Avionics','Bangalore',0,2,700000,900000,
  'https://hal-india.co.in/careers/jwm',DATE '2025-07-30','OPEN','GET',
  'DO-178C,Avionics SW,C/C++,ARINC 429');

INSERT INTO JOB_POSTING (JOB_ID,COMPANY_ID,POSITION_TITLE,DEPARTMENT,JOB_LOCATION,EXP_MIN_YEARS,EXP_MAX_YEARS,SALARY_MIN,SALARY_MAX,APPLICATION_URL,CLOSING_DATE,STATUS,JOB_TYPE,SKILLS_REQUIRED)
VALUES (SEQ_JOB.NEXTVAL,
  (SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%Cyient%' AND ROWNUM=1),
  'Associate Engineer – Avionics Software','Avionics Engineering','Hyderabad',0,1,500000,700000,
  'https://cyient.com/careers/leap',DATE '2025-06-20','OPEN','GET',
  'DO-178C,C,Python,ARINC 664,RTCA DO-160');

INSERT INTO JOB_POSTING (JOB_ID,COMPANY_ID,POSITION_TITLE,DEPARTMENT,JOB_LOCATION,EXP_MIN_YEARS,EXP_MAX_YEARS,SALARY_MIN,SALARY_MAX,APPLICATION_URL,CLOSING_DATE,STATUS,JOB_TYPE,SKILLS_REQUIRED)
VALUES (SEQ_JOB.NEXTVAL,
  (SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%ideaForge%' AND ROWNUM=1),
  'Embedded Systems Engineer – UAV','UAV Engineering','Mumbai',0,2,600000,800000,
  'https://ideaforge.in/careers',DATE '2025-07-15','OPEN','Fulltime',
  'STM32,ROS,C++,Python,Computer Vision,YOLO');

INSERT INTO JOB_POSTING (JOB_ID,COMPANY_ID,POSITION_TITLE,DEPARTMENT,JOB_LOCATION,EXP_MIN_YEARS,EXP_MAX_YEARS,SALARY_MIN,SALARY_MAX,APPLICATION_URL,CLOSING_DATE,STATUS,JOB_TYPE,SKILLS_REQUIRED,MY_APP_STATUS)
VALUES (SEQ_JOB.NEXTVAL,
  (SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%Skyroot%' AND ROWNUM=1),
  'ML Engineer – Trajectory Optimisation','GNC & Software','Hyderabad',0,2,800000,1200000,
  'https://skyroot.in/careers',DATE '2025-06-25','OPEN','Fulltime',
  'Python,PyTorch,MATLAB,scikit-learn,C++','APPLIED');

-- ── MODULE 10: SAMPLE CRM ACTIVITIES ─────────────────────────
INSERT INTO CRM_ACTIVITY (ACTIVITY_ID,COMPANY_ID,CONTACT_ID,ACTIVITY_TYPE,SUBJECT,ACTIVITY_DATE,OUTCOME,NEXT_ACTION,NEXT_ACTION_DATE,STATUS,CREATED_BY)
VALUES (SEQ_CRM_ACTIVITY.NEXTVAL,
  (SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%Hindustan%' AND ROWNUM=1),
  (SELECT CONTACT_ID FROM CRM_CONTACT WHERE COMPANY_ID=(SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%Hindustan%' AND ROWNUM=1) AND ROWNUM=1),
  'CALL','GET Programme 2025 HR Enquiry',DATE '2025-06-10',
  'HR confirmed August intake, 15 GET seats in Avionics','Send resume by June 20',DATE '2025-06-20','OPEN',
  (SELECT USER_ID FROM ERP_USERS WHERE USERNAME='mahin'));

INSERT INTO CRM_ACTIVITY (ACTIVITY_ID,COMPANY_ID,CONTACT_ID,ACTIVITY_TYPE,SUBJECT,ACTIVITY_DATE,OUTCOME,NEXT_ACTION,NEXT_ACTION_DATE,STATUS,CREATED_BY)
VALUES (SEQ_CRM_ACTIVITY.NEXTVAL,
  (SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%Cyient%' AND ROWNUM=1),
  (SELECT CONTACT_ID FROM CRM_CONTACT WHERE COMPANY_ID=(SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%Cyient%' AND ROWNUM=1) AND ROWNUM=1),
  'EMAIL','LEAP Programme Application Follow-Up',DATE '2025-06-08',
  'Auto-reply received, application in review','Follow up June 15',DATE '2025-06-15','OPEN',
  (SELECT USER_ID FROM ERP_USERS WHERE USERNAME='mahin'));

-- ── MODULE 6: SAMPLE SUPPLIERS ────────────────────────────────
INSERT INTO SUP_SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,PRODUCTS_OFFERED,CERTIFICATIONS,CITY,STATE,CONTACT_PERSON,APPROVAL_STATUS,AUDIT_STATUS)
VALUES (SEQ_SUPPLIER.NEXTVAL,'MIDHANI','Titanium alloys, superalloys, aerospace-grade steel','AS9100D,ISO 9001,NADCAP','Hyderabad','Telangana','procurement@midhani.gov.in','APPROVED','CLEARED');

INSERT INTO SUP_SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,PRODUCTS_OFFERED,CERTIFICATIONS,CITY,STATE,CONTACT_PERSON,APPROVAL_STATUS,AUDIT_STATUS)
VALUES (SEQ_SUPPLIER.NEXTVAL,'Godrej Aerospace','Precision machined components, space structures','AS9100D,NADCAP,ISO 9001','Mumbai','Maharashtra','aerospace@godrej.com','APPROVED','CLEARED');

INSERT INTO SUP_SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,PRODUCTS_OFFERED,CERTIFICATIONS,CITY,STATE,CONTACT_PERSON,APPROVAL_STATUS,AUDIT_STATUS)
VALUES (SEQ_SUPPLIER.NEXTVAL,'Dynamatic Technologies','Aerospace structural assemblies, hydraulics','AS9100D,ISO 9001,DGAQA','Bangalore','Karnataka','aero@dynamatic.com','APPROVED','CLEARED');

-- ── MODULE 7: SAMPLE PROJECTS ─────────────────────────────────
INSERT INTO PRJ_PROJECT (PROJECT_ID,COMPANY_ID,PROJECT_NAME,PROJECT_SECTOR,START_DATE,COMPLETION_DATE,PROJECT_VALUE,VALUE_CURRENCY,STATUS,KEY_TECHNOLOGIES)
VALUES (SEQ_PROJECT.NEXTVAL,
  (SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%Hindustan%' AND ROWNUM=1),
  'Tejas Mk1A – 83 Aircraft Production Programme','DEFENCE',
  DATE '2021-01-01',DATE '2028-12-31',480000000000,'INR','ONGOING',
  'Avionics,EW suite,RD-93 engine,AESA radar');

INSERT INTO PRJ_PROJECT (PROJECT_ID,COMPANY_ID,PROJECT_NAME,PROJECT_SECTOR,START_DATE,COMPLETION_DATE,PROJECT_VALUE,VALUE_CURRENCY,STATUS,KEY_TECHNOLOGIES)
VALUES (SEQ_PROJECT.NEXTVAL,
  (SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%ISRO%' AND ROWNUM=1),
  'Gaganyaan Human Spaceflight Mission','SPACE',
  DATE '2019-06-01',DATE '2025-12-31',100000000000,'INR','ONGOING',
  'Crew module,Life support,Escape system,LVM3 rocket');

INSERT INTO PRJ_PROJECT (PROJECT_ID,COMPANY_ID,PROJECT_NAME,PROJECT_SECTOR,START_DATE,COMPLETION_DATE,PROJECT_VALUE,VALUE_CURRENCY,STATUS,KEY_TECHNOLOGIES)
VALUES (SEQ_PROJECT.NEXTVAL,
  (SELECT COMPANY_ID FROM MST_COMPANY WHERE COMPANY_NAME LIKE '%Skyroot%' AND ROWNUM=1),
  'Vikram-1 Orbital Launch Vehicle','SPACE',
  DATE '2023-01-01',DATE '2025-12-31',0,'INR','ONGOING',
  'Liquid engine,3D-printed components,GNC software,Carbon fibre structure');

COMMIT;
